name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
        
    - name: Fetch Source
      run: 
         go get "github.com/golang/protobuf/proto"
         go get "github.com/v2ray/v2ray-core/app/router"
         go get "github.com/v2ray/v2ray-core/infra/conf"

    - name: Build
      run: go build -v ./...
    
    - name: GenerateRun
      run: ./V2SiteIP

    - name: Test
      run: go test -v ./...
