name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
        
    - name: Fetch Source
      run: go get -insecure -u "github.com/golang/protobuf/proto"
    
    - name: Fetch SourceV2Ray
      run: go get -insecure -u "github.com/v2ray/v2ray-core/app/router"
      
    - name: Fetch Source Conf
      run: go get -insecure -u "github.com/v2ray/v2ray-core/infra/conf"
      
    - name: Build
      run: go build -v ./..
      
    - name: GenerateRun
      run: ./V2SiteIP
