name: Build V2Ray rules dat files
on:
#   workflow_dispatch:
#   schedule:
#     - cron: "0 20 * * *"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/go.yaml"
      - "data/**"
      - "main.go"
      - "source.yaml"
      - "!**/README.md"
      - "!rules.zip"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go 1.x.y
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        shell: bash

      - name: Checkout https://github.com/SwordJason/V2SiteIP
        uses: actions/checkout@v2.3.4
        with:
          repository: SwordJason/V2SiteIP
          path: v2siteip

      - name: Build GeoSiteIP file
        run: |
          cd v2siteip || exit 1
          go run main.go --dataPath=./data/
          
      - name: Move and zip files and generate sha256 hash
        run: |
          cd v2siteip || exit 1
          install -Dp ./v2ip.dat ./publish/v2ip.dat
          install -Dp ./v2site.dat ./publish/v2site.dat
          install -Dp ./v2map.txt ./publish/v2map.txt
          install -Dp ./v2yaml.yaml ./publish/v2yaml.yaml
          cd ./publish || exit 1
          sha256sum v2ip.dat > v2ip.dat.sha256sum
          sha256sum v2site.dat > v2site.dat.sha256sum
          zip rules.zip v2ip.dat v2site.dat v2map.txt v2yaml.yaml v2ip.dat.sha256sum v2site.dat.sha256sum
          install -Dp ./rules.zip ../rules.zip
      
      - name: Git push to main
        run: |
           cd v2siteip || exit 1
           git config --local user.name "actions"
           git config --local user.email "action@github.com"
           git add ./rules.zip
           git commit -m "${{ env.RELEASE_NAME }}"
           git push

      - name: Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            ./v2siteip/publish/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Git push assets to "release" branch
        run: |
          cd v2siteip/publish || exit 1
          git init
          git config --local user.name "actions"
          git config --local user.email "action@github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release
